# Generated by Django 3.0.6 on 2020-06-09 21:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('news', '0004_auto_20200605_1354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at', 'title'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='news',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
